name: Style Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: erlang:23.2

    steps:
      - uses: actions/checkout@v1
      - run: |
          ./scripts/elvis-check.sh $GITHUB_BASE_REF
      - run: |
          make erlfmt-check
